name: test
on:
  push:
    tags:
      - v*
    branches: 
      - main
  pull_request:
    branches: 
      - main
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: go test -v ./... 

  codecov:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate coverage report
        run: |
          go version
          go test `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
          verbose: true
